# SwiftLint Configuration for SpeakFlow

excluded:
  - .build
  - Package.swift
  - Sources/LiveE2E
  - Sources/DeepgramE2E

disabled_rules:
  - trailing_whitespace  # Will fix these automatically

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional

line_length:
  warning: 150
  error: 300

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - i
    - j
    - k
    - x
    - y
    - z
    - p
    - b
    - s
    - f
    - r
    - m
    - id
    - rq
    - ck
    - ad
    - tk
    - bd
    - by
    - sr
    - sz
    - d
    - c
    - t
    - a
    - e
    - n

large_tuple:
  warning: 4
  error: 5

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 500
  error: 800

file_length:
  warning: 1500
  error: 2000
