#!/usr/bin/env bash
set -euo pipefail

unset -f git 2>/dev/null || true

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

export SWIFTPM_MODULECACHE_OVERRIDE="${SWIFTPM_MODULECACHE_OVERRIDE:-$ROOT_DIR/.build/module-cache}"
export CLANG_MODULE_CACHE_PATH="${CLANG_MODULE_CACHE_PATH:-$ROOT_DIR/.build/clang-module-cache}"
mkdir -p "$SWIFTPM_MODULECACHE_OVERRIDE" "$CLANG_MODULE_CACHE_PATH" .build

PASS_COUNT=0
FAIL_COUNT=0
SKIP_COUNT=0

# ────────────────────────────────────────────────────
# Noise Rejection E2E Suite
#
# Verifies that non-human audio does NOT trigger
# transcription API calls:
#   - White noise
#   - 440Hz sine tone
#   - Multitone (chord)
#   - Silence
#
# Audio files: /tmp/sf_test_*.wav (generated by
#   /tmp/sf_generate_test_audio.py or inline ffmpeg)
#
# Each test plays audio through afplay while the
# LiveE2E binary records via microphone. In noise
# rejection mode (skipSilentChunks=true), the VAD
# should reject non-speech audio → 0 API chunks.
# ────────────────────────────────────────────────────

TEST_AUDIO_DIR="/tmp"

generate_test_audio() {
    echo "Generating test audio files..."

    # White noise (10s)
    if ! ffmpeg -y -f lavfi -i "anoisesrc=c=pink:r=16000:a=0.5" -t 10 \
        "$TEST_AUDIO_DIR/sf_test_whitenoise.wav" > /dev/null 2>&1; then
        echo "WARNING: Could not generate white noise WAV"
    fi

    # 440Hz sine tone (10s)
    if ! ffmpeg -y -f lavfi -i "sine=f=440:r=16000:d=10" -filter:a "volume=0.5" \
        "$TEST_AUDIO_DIR/sf_test_tone440.wav" > /dev/null 2>&1; then
        echo "WARNING: Could not generate 440Hz tone WAV"
    fi

    # Multitone chord (10s)
    if ! ffmpeg -y -f lavfi \
        -i "sine=f=261:r=16000:d=10" -i "sine=f=330:r=16000:d=10" \
        -i "sine=f=392:r=16000:d=10" -i "sine=f=523:r=16000:d=10" \
        -filter_complex "amix=inputs=4:duration=longest,volume=0.4" \
        "$TEST_AUDIO_DIR/sf_test_multitone.wav" > /dev/null 2>&1; then
        echo "WARNING: Could not generate multitone WAV"
    fi

    # Silence (10s)
    if ! ffmpeg -y -f lavfi -i "anullsrc=r=16000:cl=mono" -t 10 \
        "$TEST_AUDIO_DIR/sf_test_silence.wav" > /dev/null 2>&1; then
        echo "WARNING: Could not generate silence WAV"
    fi
}

run_case() {
    local name="$1"
    local audio_file="$2"
    local timeout="${3:-25}"

    if [[ ! -f "$audio_file" ]]; then
        SKIP_COUNT=$((SKIP_COUNT + 1))
        echo ""
        echo "⚠️  SKIPPED: $name (audio file not found: $audio_file)"
        return
    fi

    local slug
    slug="$(echo "$name" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-')"
    local output_file
    output_file="$(mktemp "/tmp/speakflow-noise-${slug}.XXXX.log")"

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "TEST: $name"
    echo "Audio: $audio_file"
    echo "Output: $output_file"

    set +e
    (
        export SPEAKFLOW_E2E_TEST_NOISE_REJECTION=1
        export SPEAKFLOW_E2E_AUDIO_FILE_PATH="$audio_file"
        export SPEAKFLOW_E2E_RECORD_SECONDS=12
        export SPEAKFLOW_E2E_TIMEOUT_SECONDS="$timeout"
        export SPEAKFLOW_E2E_TEST_AUTO_END=false

        swift run --disable-sandbox SpeakFlowLiveE2E
    ) >"$output_file" 2>&1
    local rc=$?
    set -e

    local chunk_count
    chunk_count="$(grep -c '^chunk #' "$output_file" || echo 0)"

    if [[ $rc -eq 0 && $chunk_count -eq 0 ]]; then
        PASS_COUNT=$((PASS_COUNT + 1))
        echo "✅ PASS ($name) — 0 chunks sent to API"
    else
        FAIL_COUNT=$((FAIL_COUNT + 1))
        echo "❌ FAIL ($name) — ${chunk_count} chunk(s) sent, exit=$rc"
        echo "Last output lines:"
        tail -n 20 "$output_file"
    fi
}

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  SpeakFlow Noise Rejection E2E"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Ensure test audio exists
NEED_GENERATE=false
for f in whitenoise tone440 multitone silence; do
    if [[ ! -f "$TEST_AUDIO_DIR/sf_test_${f}.wav" ]]; then
        NEED_GENERATE=true
        break
    fi
done

if $NEED_GENERATE; then
    if command -v ffmpeg &>/dev/null; then
        generate_test_audio
    elif [[ -f /tmp/sf_generate_test_audio.py ]]; then
        echo "Generating test audio with Python..."
        python3 /tmp/sf_generate_test_audio.py
    else
        echo "ERROR: ffmpeg not found and no Python generator. Cannot create test audio."
        echo "Install ffmpeg or run: python3 /tmp/sf_generate_test_audio.py"
        exit 1
    fi
fi

# 1) White noise → NO API call
run_case "White noise rejection" "$TEST_AUDIO_DIR/sf_test_whitenoise.wav"

# 2) 440Hz sine tone → NO API call
run_case "440Hz tone rejection" "$TEST_AUDIO_DIR/sf_test_tone440.wav"

# 3) Multitone chord → NO API call
run_case "Multitone chord rejection" "$TEST_AUDIO_DIR/sf_test_multitone.wav"

# 4) Silence → NO API call
run_case "Silence rejection" "$TEST_AUDIO_DIR/sf_test_silence.wav"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Noise rejection E2E summary: ${PASS_COUNT} passed, ${FAIL_COUNT} failed, ${SKIP_COUNT} skipped"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [[ $FAIL_COUNT -gt 0 ]]; then
    exit 1
fi
